### ISSUE TITLE
GitHub-LFS

### ISSUE THREAD

**Issue by rituparna-ui** [samuelmarina/is-even#101]
![image](https://user-images.githubusercontent.com/54203587/129929319-2b376668-ab0b-4e2e-b8bf-71fbbf9846f9.png)

i had written lines upto 499000
but file size exceeds github limit

What do i do now ?

**Comment by vksonagara** [comment]
Create a new file and function for numbers greater than 375000

**Comment by rituparna-ui** [comment]
Good idea @vksonagara

**Comment by rituparna-ui** [comment]
@samuelmarina should i ?

**Comment by NikolayVasilev** [comment]
Easy - create a lib that gives you the string of the number and use that in this one. Should bring the file size to about 20MB... give or take...

**Comment by wmattei** [comment]
I don't think is worth it to make this package smaller. I mean, how can someone possible want something smaller??

**Comment by NikolayVasilev** [comment]
Well... If it's smaller, we'll have more ground to cover even MORE numbers. And more is always better than less... Unless we talk about size...
