### ISSUE TITLE
Can you write an `is-prime` package?

### ISSUE THREAD

**Issue by JiaJiaJiang** [samuelmarina/is-even#135]
It's much harder for people!

**Comment by sumantopal07** [comment]
what is prime? is it a number when it is in its prime power?....like 69

**Comment by JiaJiaJiang** [comment]
This 'prime': https://en.wikipedia.org/wiki/Prime_number.
Unfortunately 69 is not a prime.

**Comment by agoudbg** [comment]
I have made this https://github.com/agoudbg/is-Prime
