### ISSUE TITLE
everyone gangsta until you realize it doesn't even work. LMFAO

### ISSUE THREAD

**Issue by arpan-lol** [samuelmarina/is-even#169]
![image](https://user-images.githubusercontent.com/64348757/130315541-f9edefcd-b76f-41bd-b704-0cf02e40f228.png)

Honestly I hate to say it doesn't even work after all of the shit because of the file size but here we are

**Comment by arpan-lol** [comment]
[check it out for yourself](https://replit.com/@MeMasterMind/e#index.js)

**Comment by mrmahendra27** [comment]
my browser broke when i tried to view the index file
