### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by orhanerday** [samuelmarina/is-even#37]
I got `A stack trace for this error that could not be retrieved because the stack was already called.` error.

**Comment by jonathonball** [comment]
```
➤ git clone git@github.com:samuelmarina/is-even.git
Cloning into 'is-even'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 53 (delta 14), reused 31 (delta 6), pack-reused 0
Receiving objects: 100% (53/53), 4.48 MiB | 583.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.
```
Create test script
```
➤ cat test.js 
var isEven = require('./index.js');
console.log(isEven(99999));
```
Verify node version is latest LTS
```
➤ node -v
v14.17.5
```
and I got the same error
```
➤ node test.js
internal/modules/cjs/loader.js:988
    compiled = compileFunction(
               ^

RangeError: Maximum call stack size exceeded
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jonathanb/project-environments/is-even/test.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
``` 
this whole repo is a troll.

**Comment by samuelmarina** [comment]
Fix it then...

**Comment by AirmanEpic** [comment]
> this whole repo is a troll.

You know, this kind of negativity and toxicity is why people don't contribute to open source projects. If you can't get it working on your machine, that's not a reason to insult the devs.

**Comment by vincens2005** [comment]
I'm having this error as well. :(

I really wanted to use this library because it seemed really useful but I just can't seem to get it working.

**Comment by AirmanEpic** [comment]
fixed with https://github.com/samuelmarina/is-even/pull/59

let me know if that's fixing the problem for you guys too.

**Comment by orhanerday** [comment]
Thanks @AirmanEpic  , issue closed. 

Thank you for your attention.

**Comment by jonathonball** [comment]
> > this whole repo is a troll.
> 
> You know, this kind of negativity and toxicity is why people don't contribute to open source projects. If you can't get it working on your machine, that's not a reason to insult the devs.

Lol. Did you even look at the code? It's a giant branching if/else tree and it's limited to the first million numbers. You should not put this in your project.

**Comment by AirmanEpic** [comment]
> > > this whole repo is a troll.
> > 
> > 
> > You know, this kind of negativity and toxicity is why people don't contribute to open source projects. If you can't get it working on your machine, that's not a reason to insult the devs.
> 
> Lol. Did you even look at the code? It's a giant branching if/else tree and it's limited to the first million numbers. The file is over 40mbs. You should not put this in your project.
> 
> In addition we already have a popular is-odd library in npm that works on arbitrary numbers. There is literally no need for this repository to exist.

Look, I personally contributed to this project and I'm trying to not take your comments about my hard work personally. I wrote over 1,100,000 lines (I counted!) for this project. So if you have such negativity in your heart just, you know, don't participate.

**Comment by jonathonball** [comment]
> > > > this whole repo is a troll.
> > > 
> > > 
> > > You know, this kind of negativity and toxicity is why people don't contribute to open source projects. If you can't get it working on your machine, that's not a reason to insult the devs.
> > 
> > 
> > Lol. Did you even look at the code? It's a giant branching if/else tree and it's limited to the first million numbers. The file is over 40mbs. You should not put this in your project.
> > In addition we already have a popular is-odd library in npm that works on arbitrary numbers. There is literally no need for this repository to exist.
> 
> Look, I personally contributed to this project and I'm trying to not take your comments about my hard work personally. I wrote over 1,100,000 lines (I counted!) for this project. So if you have such negativity in your heart just, you know, don't participate.

Oh, you're trolling. I'm sorry, continue on.
