### ISSUE TITLE
Quick (unrelated) question

### ISSUE THREAD

**Issue by Meaxis** [samuelmarina/is-even#60]
Did you code this yourself, or did you use software to code it?

**Comment by AirmanEpic** [comment]
I can't speak for the other devs but I copied and pasted each line and edited the number/boolean on that line. It's faster than hand-coding everything.

**Comment by samuelmarina** [comment]
I wrote it using a telegraph

**Comment by Meaxis** [comment]
_Yep, this is by far one of my favorite repos._
