### ISSUE TITLE
Well... uhhh

### ISSUE THREAD

**Issue by harushiki** [samuelmarina/is-even#98]
![image](https://user-images.githubusercontent.com/68916385/129923898-36729560-1f8d-494b-ab25-6d55b2a86e4b.png)

**Comment by harushiki** [comment]
It was just few more.... just upto 426969

**Comment by nafisfaysal** [comment]
in case you're wondering what's the last number.

![image](https://user-images.githubusercontent.com/7595238/129925600-a1fdd375-6239-4bee-992e-78dfee3aa628.png)

**Comment by AirmanEpic** [comment]
in JS we support requires so feel free to break the file into smaller chunks and require them as needed =)

**Comment by harushiki** [comment]
hmmm that's actually a pretty good idea
